project:
  type: website

website:
  title: "ISSS608 Project (Group 3)"
  image: "images/ship.jpg"
  favicon: "images/fishhook.png"
  navbar:
    logo: "images/fishhook.png"
    title: false
    collapse-below: lg
    search: true
    right:
      - text: "The Team"
        href: about.html
      - text: "Project Proposal"
        href: Proposal.html
      - text: "Project Overview"
        href: project_overview.html
      - text: "Shiny App"
        menu:
          - text: "User Guide"
            href: userguide.html
          - text: "Shiny App"
            href: Shinyapp.html
      - text: "Project Poster"
        href: Poster.html


format:
  html:
    grid: 
      margin-width: 180px
    theme: cosmo
    highlight-style: github
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    toc: true

editor: visual
  